import { random } from "lodash";
import { PostItemProps } from "../main/home/content/PostItem";

export const getPostsMock = (page?: number): PostItemProps[] => [
  {
    id: random(99).toString(),
    userName: "jiayhnz",
    ageTime: "2 jam",
    profileImageUrl: "https://cache.lahelu.com/avatar-UjDHld6ch-25768",
    content: "Namanya juga hewan",
    mediaUrl: "https://cache.lahelu.com/image-PSdZmwWUb-75503",
    mediaType: "image",
    tags: ["lucu"],
    niceVotes: 340,
    badVotes: 12,
    commentCount: 55,
    isFocused: false,
  },
  {
    id: random(99).toString(),
    userName: "dalangkun",
    ageTime: "4 jam",
    profileImageUrl: "https://cache.lahelu.com/avatar-UKn00db3s-54146",
    content: "Udah lama gak bikin meme di lahelu😁",
    mediaUrl: "https://cache.lahelu.com/image-PnsuiPEfa-63623",
    mediaType: "image",
    tags: ["lucu"],
    niceVotes: 340,
    badVotes: 12,
    commentCount: 55,
    isFocused: false,
  },
  {
    id: random(99).toString(),
    userName: "skibidi_berry_berry",
    ageTime: "8 jam",
    profileImageUrl: "https://cache.lahelu.com/avatar-U9BkkWDzL-38613",
    content: "Udah lama gak bikin meme di lahelu😁",
    mediaUrl: "https://cache.lahelu.com/video-PjwtrSgPD-61101",
    mediaType: "video",
    tags: ["video", "laugh", "feelgood"],
    niceVotes: 420,
    badVotes: 10,
    commentCount: 65,
    isFocused: false,
  },
  {
    id: random(99).toString(),
    userName: "frostfire47",
    ageTime: "10 jam",
    profileImageUrl:
      "https://lh3.googleusercontent.com/a/AGNmyxaurbpTyEkT7O8eRexEjhjDQO4X71aXJX4jSMVq=s96-c",
    content: "Ambatunat",
    mediaUrl: "https://cache.lahelu.com/video-P7e4a0E7C-76359",
    mediaType: "video",
    tags: ["video", "laugh", "feelgood"],
    niceVotes: 420,
    badVotes: 10,
    commentCount: 65,
    isFocused: false,
  },
  {
    id: random(99).toString(),
    userName: "wolvies",
    ageTime: "10 jam",
    profileImageUrl: "https://cache.lahelu.com/video-Pdou5l4p6-66392",
    content: "Hahaha, ngakak pas lihat ini!",
    mediaUrl: "https://cache.lahelu.com/video-PTBrDG2P8-70797",
    mediaType: "video",
    tags: ["humor", "rofl", "memeoftheday"],
    niceVotes: 180,
    badVotes: 6,
    commentCount: 25,
    isFocused: false,
  },
];
